# ========== CONFIGMAPS (init.sql scripts) ==========
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-garage-initdb
  namespace: argocd
data:
  init.sql: |
    CREATE DATABASE "garage-service";

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-initdb
  namespace: argocd
data:
  init.sql: |
    CREATE DATABASE "user-service";

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-vehicle-owner-initdb
  namespace: argocd
data:
  init.sql: |
    CREATE DATABASE "vehicle-owner-service";

# ========== GARAGE SERVICE POSTGRES ==========
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-garage-pvc
  namespace: argocd
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-garage
  namespace: argocd
  labels:
    app: postgres-garage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-garage
  template:
    metadata:
      labels:
        app: postgres-garage
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Root@123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-garage-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgres-garage-storage
          persistentVolumeClaim:
            claimName: postgres-garage-pvc
        - name: init-script
          configMap:
            name: postgres-garage-initdb

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-garage
  namespace: argocd
spec:
  selector:
    app: postgres-garage
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

# ========== USER SERVICE POSTGRES ==========
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
  namespace: argocd
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-user
  namespace: argocd
  labels:
    app: postgres-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Root@123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-user-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgres-user-storage
          persistentVolumeClaim:
            claimName: postgres-user-pvc
        - name: init-script
          configMap:
            name: postgres-user-initdb

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: argocd
spec:
  selector:
    app: postgres-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

# ========== VEHICLE OWNER POSTGRES ==========
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vehicle-owner-pvc
  namespace: argocd
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-vehicle-owner
  namespace: argocd
  labels:
    app: postgres-vehicle-owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-vehicle-owner
  template:
    metadata:
      labels:
        app: postgres-vehicle-owner
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Root@123"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-vehicle-owner-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgres-vehicle-owner-storage
          persistentVolumeClaim:
            claimName: postgres-vehicle-owner-pvc
        - name: init-script
          configMap:
            name: postgres-vehicle-owner-initdb

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-vehicle-owner
  namespace: argocd
spec:
  selector:
    app: postgres-vehicle-owner
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

# ========== MYSQL NOTIFICATION SERVICE ==========
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-notification-pvc
  namespace: argocd
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-notification
  namespace: argocd
  labels:
    app: mysql-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-notification
  template:
    metadata:
      labels:
        app: mysql-notification
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Root@123"
            - name: MYSQL_DATABASE
              value: "notification-service"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-notification-storage
      volumes:
        - name: mysql-notification-storage
          persistentVolumeClaim:
            claimName: mysql-notification-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-notification
  namespace: argocd
spec:
  selector:
    app: mysql-notification
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
