apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: argocd
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/ctse-assignment-y4-se/notification-service:20250420053228
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/garage"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Root@123"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"