apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: argocd
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9091
    - name: grpc
      protocol: TCP
      port: 7071
      targetPort: 7071
  type: ClusterIP
