apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: argocd
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/ctse-assignment-y4-se/frontend:20250509162213
          ports:
            - containerPort: 5000
