apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: argocd
spec:
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
