apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: argocd
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9092
    - name: grpc
      protocol: TCP
      port: 7072
      targetPort: 7072
  type: ClusterIP
