apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-vehicle-owner-service
  labels:
    app: postgres-vehicle-owner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-vehicle-owner-service
  template:
    metadata:
      labels:
        app: postgres-vehicle-owner-service
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "vehicle-owner-service"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Root@123"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-vehicle-owner-service
spec:
  selector:
    app: postgres-vehicle-owner-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
