apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-owner-service
  labels:
    app: vehicle-owner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-owner-service
  template:
    metadata:
      labels:
        app: vehicle-owner-service
    spec:
      containers:
        - name: vehicle-owner-service
          image: ghcr.io/ctse-assignment-y4-se/vehicle-owner-service:latest
          ports:
            - containerPort: 9093
            - containerPort: 7073
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-vehicle-owner-service:5432/vehicle-owner-service"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Root@123"
            - name: GRPC_SERVER_PORT
              value: "7073"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: vehicle-owner-service
spec:
  selector:
    app: vehicle-owner-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9093
    - name: grpc
      protocol: TCP
      port: 7073
      targetPort: 7073
  type: ClusterIP
