apiVersion: v1
kind: Service
metadata:
  name: garage-service
  namespace: argocd
spec:
  selector:
    app: garage-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9090
    - name: grpc
      protocol: TCP
      port: 7070
      targetPort: 7070
  type: ClusterIP
