---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx-conf
  namespace: argocd
data:
  default.conf: |
    server {
      listen 80;

      # ── User service (strips /user/)
      location /user/ {
        proxy_pass http://user-service.argocd.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
      }

      # ── Vehicle-owner service (strips /vehicle-owner/)
      location /vehicle-owner/ {
        proxy_pass http://vehicle-owner-service.argocd.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
      }

      # ── Garage service (strips /garage/)
      location /garage/ {
        proxy_pass http://garage-service.argocd.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
      }

      # ── Notification service (strips /notification/)
      location /notification/ {
        proxy_pass http://notification-service.argocd.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
      }

      # ── Frontend (everything else)
      location / {
        proxy_pass http://frontend.argocd.svc.cluster.local/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: argocd
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: gateway-nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: argocd
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
