apiVersion: v1
kind: Service
metadata:
  name: vehicle-owner-service
  namespace: argocd
spec:
  selector:
    app: vehicle-owner-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9093
  type: ClusterIP
